name: Build and Deploy Application
on: 
  push:
    branches: 
    - main
jobs:
  Test-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome to workflows"
      - run: echo "Event that triggered this worklfow was ${{ github.event_name }}"

